// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDienaRotOP-uL_k-Xb6SYYypG-CoK5nWQ',
    appId: '1:713687848419:web:9805a3340b55b2e93b7cd6',
    messagingSenderId: '713687848419',
    projectId: 'mahavision-toll',
    authDomain: 'mahavision-toll.firebaseapp.com',
    storageBucket: 'mahavision-toll.firebasestorage.app',
    measurementId: 'G-ZS7P0KER8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDMgt2SOy9uW1_VNo5TYLUq-2-T3OtZm8',
    appId: '1:713687848419:android:2a71ca97846e789f3b7cd6',
    messagingSenderId: '713687848419',
    projectId: 'mahavision-toll',
    storageBucket: 'mahavision-toll.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtYjiwZ-F9q-BymDPdNZyfwMI7eBWES7U',
    appId: '1:713687848419:ios:ec8bb0f382a3bc0d3b7cd6',
    messagingSenderId: '713687848419',
    projectId: 'mahavision-toll',
    storageBucket: 'mahavision-toll.firebasestorage.app',
    iosBundleId: 'com.example.lomba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtYjiwZ-F9q-BymDPdNZyfwMI7eBWES7U',
    appId: '1:713687848419:ios:ec8bb0f382a3bc0d3b7cd6',
    messagingSenderId: '713687848419',
    projectId: 'mahavision-toll',
    storageBucket: 'mahavision-toll.firebasestorage.app',
    iosBundleId: 'com.example.lomba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDienaRotOP-uL_k-Xb6SYYypG-CoK5nWQ',
    appId: '1:713687848419:web:3f343915e0fa2d523b7cd6',
    messagingSenderId: '713687848419',
    projectId: 'mahavision-toll',
    authDomain: 'mahavision-toll.firebaseapp.com',
    storageBucket: 'mahavision-toll.firebasestorage.app',
    measurementId: 'G-G5KVLNTE7B',
  );
}
